// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HallChatMessage.proto

package info.xiaomo.server.shared.protocol.hall.chat;

public interface ChatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ChatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *消息id
   * </pre>
   *
   * <code>.MsgId msgId = 1;</code>
   * @return The enum numeric value on the wire for msgId.
   */
  int getMsgIdValue();
  /**
   * <pre>
   *消息id
   * </pre>
   *
   * <code>.MsgId msgId = 1;</code>
   * @return The msgId.
   */
  info.xiaomo.server.shared.protocol.msg.MsgId getMsgId();

  /**
   * <pre>
   *发送者ID
   * </pre>
   *
   * <code>int64 senderId = 2;</code>
   * @return The senderId.
   */
  long getSenderId();

  /**
   * <pre>
   *发送者头像
   * </pre>
   *
   * <code>string senderHead = 3;</code>
   * @return The senderHead.
   */
  java.lang.String getSenderHead();
  /**
   * <pre>
   *发送者头像
   * </pre>
   *
   * <code>string senderHead = 3;</code>
   * @return The bytes for senderHead.
   */
  com.google.protobuf.ByteString
      getSenderHeadBytes();

  /**
   * <pre>
   *发送者昵称
   * </pre>
   *
   * <code>string senderNick = 4;</code>
   * @return The senderNick.
   */
  java.lang.String getSenderNick();
  /**
   * <pre>
   *发送者昵称
   * </pre>
   *
   * <code>string senderNick = 4;</code>
   * @return The bytes for senderNick.
   */
  com.google.protobuf.ByteString
      getSenderNickBytes();

  /**
   * <pre>
   *聊天类型
   * </pre>
   *
   * <code>.ChatType chatType = 5;</code>
   * @return The enum numeric value on the wire for chatType.
   */
  int getChatTypeValue();
  /**
   * <pre>
   *聊天类型
   * </pre>
   *
   * <code>.ChatType chatType = 5;</code>
   * @return The chatType.
   */
  info.xiaomo.server.shared.protocol.hall.chat.ChatType getChatType();

  /**
   * <pre>
   *聊天消息
   * </pre>
   *
   * <code>string msg = 6;</code>
   * @return The msg.
   */
  java.lang.String getMsg();
  /**
   * <pre>
   *聊天消息
   * </pre>
   *
   * <code>string msg = 6;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
