// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BydrRoomMessage.proto

package info.xiaomo.server.shared.protocol.gameserver.room;

public interface FishEnterRoomResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FishEnterRoomResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *消息id
   * </pre>
   *
   * <code>.MsgId msgId = 1;</code>
   * @return The enum numeric value on the wire for msgId.
   */
  int getMsgIdValue();
  /**
   * <pre>
   *消息id
   * </pre>
   *
   * <code>.MsgId msgId = 1;</code>
   * @return The msgId.
   */
  info.xiaomo.server.shared.protocol.msg.MsgId getMsgId();

  /**
   * <pre>
   *进入的鱼群
   * </pre>
   *
   * <code>repeated .FishInfo fishInfo = 2;</code>
   */
  java.util.List<info.xiaomo.server.shared.protocol.gameserver.room.FishInfo> 
      getFishInfoList();
  /**
   * <pre>
   *进入的鱼群
   * </pre>
   *
   * <code>repeated .FishInfo fishInfo = 2;</code>
   */
  info.xiaomo.server.shared.protocol.gameserver.room.FishInfo getFishInfo(int index);
  /**
   * <pre>
   *进入的鱼群
   * </pre>
   *
   * <code>repeated .FishInfo fishInfo = 2;</code>
   */
  int getFishInfoCount();
  /**
   * <pre>
   *进入的鱼群
   * </pre>
   *
   * <code>repeated .FishInfo fishInfo = 2;</code>
   */
  java.util.List<? extends info.xiaomo.server.shared.protocol.gameserver.room.FishInfoOrBuilder> 
      getFishInfoOrBuilderList();
  /**
   * <pre>
   *进入的鱼群
   * </pre>
   *
   * <code>repeated .FishInfo fishInfo = 2;</code>
   */
  info.xiaomo.server.shared.protocol.gameserver.room.FishInfoOrBuilder getFishInfoOrBuilder(
      int index);
}
