// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BydrRoomMessage.proto

package info.xiaomo.server.shared.protocol.gameserver.room;

public interface RoomChangeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RoomChangeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *消息id
   * </pre>
   *
   * <code>.MsgId msgId = 1;</code>
   * @return The enum numeric value on the wire for msgId.
   */
  int getMsgIdValue();
  /**
   * <pre>
   *消息id
   * </pre>
   *
   * <code>.MsgId msgId = 1;</code>
   * @return The msgId.
   */
  info.xiaomo.server.shared.protocol.msg.MsgId getMsgId();

  /**
   * <pre>
   *房间信息
   * </pre>
   *
   * <code>.RoomInfo roomInfo = 2;</code>
   * @return Whether the roomInfo field is set.
   */
  boolean hasRoomInfo();
  /**
   * <pre>
   *房间信息
   * </pre>
   *
   * <code>.RoomInfo roomInfo = 2;</code>
   * @return The roomInfo.
   */
  info.xiaomo.server.shared.protocol.gameserver.room.RoomInfo getRoomInfo();
  /**
   * <pre>
   *房间信息
   * </pre>
   *
   * <code>.RoomInfo roomInfo = 2;</code>
   */
  info.xiaomo.server.shared.protocol.gameserver.room.RoomInfoOrBuilder getRoomInfoOrBuilder();
}
