// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserMessage.proto

package info.xiaomo.server.shared.protocol.user;

public interface LoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 sex = 1;</code>
   * @return The sex.
   */
  int getSex();

  /**
   * <code>int64 userId = 2;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <code>string loginName = 3;</code>
   * @return The loginName.
   */
  String getLoginName();
  /**
   * <code>string loginName = 3;</code>
   * @return The bytes for loginName.
   */
  com.google.protobuf.ByteString
      getLoginNameBytes();
}
