// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HallGuildMessage.proto

package info.xiaomo.server.shared.protocol.hall.guild;

public interface GuildInfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GuildInfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *消息id
   * </pre>
   *
   * <code>.MsgId msgId = 1;</code>
   * @return The enum numeric value on the wire for msgId.
   */
  int getMsgIdValue();
  /**
   * <pre>
   *消息id
   * </pre>
   *
   * <code>.MsgId msgId = 1;</code>
   * @return The msgId.
   */
  info.xiaomo.server.shared.protocol.msg.MsgId getMsgId();

  /**
   * <pre>
   *帮会信息
   * </pre>
   *
   * <code>.GuildInfo guildInfo = 2;</code>
   * @return Whether the guildInfo field is set.
   */
  boolean hasGuildInfo();
  /**
   * <pre>
   *帮会信息
   * </pre>
   *
   * <code>.GuildInfo guildInfo = 2;</code>
   * @return The guildInfo.
   */
  info.xiaomo.server.shared.protocol.hall.guild.GuildInfo getGuildInfo();
  /**
   * <pre>
   *帮会信息
   * </pre>
   *
   * <code>.GuildInfo guildInfo = 2;</code>
   */
  info.xiaomo.server.shared.protocol.hall.guild.GuildInfoOrBuilder getGuildInfoOrBuilder();
}
