// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HallGuildMessage.proto

package info.xiaomo.server.shared.protocol.hall.guild;

public interface GuildMemberInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GuildMemberInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *角色Id
   * </pre>
   *
   * <code>int64 roleId = 1;</code>
   * @return The roleId.
   */
  long getRoleId();

  /**
   * <pre>
   *昵称
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   *昵称
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   *等级
   * </pre>
   *
   * <code>int32 level = 3;</code>
   * @return The level.
   */
  int getLevel();
}
