// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerMessage.proto

package info.xiaomo.server.shared.protocol.server;

public interface ServerEventResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ServerEventResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.MsgId msgId = 1;</code>
   * @return The enum numeric value on the wire for msgId.
   */
  int getMsgIdValue();
  /**
   * <code>.MsgId msgId = 1;</code>
   * @return The msgId.
   */
  info.xiaomo.server.shared.protocol.msg.MsgId getMsgId();

  /**
   * <pre>
   *事件类型  1踢玩家
   * </pre>
   *
   * <code>int32 type = 2;</code>
   * @return The type.
   */
  int getType();

  /**
   * <pre>
   *结果
   * </pre>
   *
   * <code>int32 result = 3;</code>
   * @return The result.
   */
  int getResult();
}
