// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageId.proto

package info.xiaomo.server.shared.protocol.msg;

/**
 * Protobuf enum {@code MsgId}
 */
public enum MsgId
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>Unknown = 0;</code>
   */
  Unknown(0),
  /**
   * <pre>
   * user group:101
   * </pre>
   *
   * <code>LoginRequest = 101001;</code>
   */
  LoginRequest(101001),
  /**
   * <code>LoginResponse = 101002;</code>
   */
  LoginResponse(101002),
  /**
   * <pre>
   * gm group: 201
   * </pre>
   *
   * <code>CloseServerRequest = 201001;</code>
   */
  CloseServerRequest(201001),
  /**
   * <code>CloseServerResponse = 201002;</code>
   */
  CloseServerResponse(201002),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>Unknown = 0;</code>
   */
  public static final int Unknown_VALUE = 0;
  /**
   * <pre>
   * user group:101
   * </pre>
   *
   * <code>LoginRequest = 101001;</code>
   */
  public static final int LoginRequest_VALUE = 101001;
  /**
   * <code>LoginResponse = 101002;</code>
   */
  public static final int LoginResponse_VALUE = 101002;
  /**
   * <pre>
   * gm group: 201
   * </pre>
   *
   * <code>CloseServerRequest = 201001;</code>
   */
  public static final int CloseServerRequest_VALUE = 201001;
  /**
   * <code>CloseServerResponse = 201002;</code>
   */
  public static final int CloseServerResponse_VALUE = 201002;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static MsgId valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static MsgId forNumber(int value) {
    switch (value) {
      case 0: return Unknown;
      case 101001: return LoginRequest;
      case 101002: return LoginResponse;
      case 201001: return CloseServerRequest;
      case 201002: return CloseServerResponse;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MsgId>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MsgId> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MsgId>() {
          public MsgId findValueByNumber(int number) {
            return MsgId.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return MessageId.getDescriptor().getEnumTypes().get(0);
  }

  private static final MsgId[] VALUES = values();

  public static MsgId valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MsgId(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:MsgId)
}

