// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GMMessage.proto

package info.xiaomo.server.shared.protocol.gm;

public final class GMMessage {
  private GMMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReqGMCloseServer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReqGMCloseServer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResGMCloseServer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResGMCloseServer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017GMMessage.proto\032\017MessageId.proto\";\n\020Re" +
      "qGMCloseServer\022\027\n\005msgId\030\001 \001(\0162\010.GMMsgId\022" +
      "\016\n\006resMsg\030\002 \001(\t\";\n\020ResGMCloseServer\022\027\n\005m" +
      "sgId\030\001 \001(\0162\010.GMMsgId\022\016\n\006resMsg\030\002 \001(\tB)\n%" +
      "info.xiaomo.server.shared.protocol.gmP\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          info.xiaomo.server.shared.protocol.msg.MessageId.getDescriptor(),
        });
    internal_static_ReqGMCloseServer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ReqGMCloseServer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReqGMCloseServer_descriptor,
        new String[] { "MsgId", "ResMsg", });
    internal_static_ResGMCloseServer_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ResGMCloseServer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResGMCloseServer_descriptor,
        new String[] { "MsgId", "ResMsg", });
    info.xiaomo.server.shared.protocol.msg.MessageId.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
