// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HallLoginMessage.proto

package info.xiaomo.server.shared.protocol.hall.login;

public final class HallLoginMessage {
  private HallLoginMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QuitRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QuitRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QuitResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QuitResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginSubGameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginSubGameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginSubGameResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginSubGameResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QuitSubGameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QuitSubGameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QuitSubGameResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QuitSubGameResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026HallLoginMessage.proto\032\017MessageId.prot" +
      "o\"\247\001\n\014LoginRequest\022\025\n\005msgId\030\001 \001(\0162\006.MsgI" +
      "d\022\017\n\007account\030\002 \001(\t\022\020\n\010password\030\003 \001(\t\022\035\n\t" +
      "loginType\030\004 \001(\0162\n.LoginType\022\021\n\tsessionId" +
      "\030\005 \001(\003\022\016\n\006gateId\030\006 \001(\005\022\n\n\002ip\030\007 \001(\t\022\017\n\007ve" +
      "rsion\030\010 \001(\t\"a\n\rLoginResponse\022\025\n\005msgId\030\001 " +
      "\001(\0162\006.MsgId\022\014\n\004isOk\030\002 \001(\010\022\013\n\003uid\030\003 \001(\003\022\013" +
      "\n\003rid\030\004 \001(\003\022\021\n\tsessionId\030\005 \001(\003\"1\n\013QuitRe" +
      "quest\022\025\n\005msgId\030\001 \001(\0162\006.MsgId\022\013\n\003rid\030\002 \001(" +
      "\003\"5\n\014QuitResponse\022\025\n\005msgId\030\001 \001(\0162\006.MsgId" +
      "\022\016\n\006result\030\002 \001(\005\"Y\n\023LoginSubGameRequest\022" +
      "\025\n\005msgId\030\001 \001(\0162\006.MsgId\022\013\n\003rid\030\002 \001(\003\022\014\n\004t" +
      "ype\030\003 \001(\005\022\020\n\010gameType\030\004 \001(\005\"=\n\024LoginSubG" +
      "ameResponse\022\025\n\005msgId\030\001 \001(\0162\006.MsgId\022\016\n\006re" +
      "sult\030\002 \001(\005\"8\n\022QuitSubGameRequest\022\025\n\005msgI" +
      "d\030\001 \001(\0162\006.MsgId\022\013\n\003rid\030\002 \001(\003\"<\n\023QuitSubG" +
      "ameResponse\022\025\n\005msgId\030\001 \001(\0162\006.MsgId\022\016\n\006re" +
      "sult\030\002 \001(\005*)\n\tLoginType\022\017\n\013DefaultType\020\000" +
      "\022\013\n\007ACCOUNT\020\001B1\n-info.xiaomo.server.shar" +
      "ed.protocol.hall.loginP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          info.xiaomo.server.shared.protocol.msg.MessageId.getDescriptor(),
        });
    internal_static_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginRequest_descriptor,
        new java.lang.String[] { "MsgId", "Account", "Password", "LoginType", "SessionId", "GateId", "Ip", "Version", });
    internal_static_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginResponse_descriptor,
        new java.lang.String[] { "MsgId", "IsOk", "Uid", "Rid", "SessionId", });
    internal_static_QuitRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_QuitRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QuitRequest_descriptor,
        new java.lang.String[] { "MsgId", "Rid", });
    internal_static_QuitResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_QuitResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QuitResponse_descriptor,
        new java.lang.String[] { "MsgId", "Result", });
    internal_static_LoginSubGameRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_LoginSubGameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginSubGameRequest_descriptor,
        new java.lang.String[] { "MsgId", "Rid", "Type", "GameType", });
    internal_static_LoginSubGameResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_LoginSubGameResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginSubGameResponse_descriptor,
        new java.lang.String[] { "MsgId", "Result", });
    internal_static_QuitSubGameRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_QuitSubGameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QuitSubGameRequest_descriptor,
        new java.lang.String[] { "MsgId", "Rid", });
    internal_static_QuitSubGameResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_QuitSubGameResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QuitSubGameResponse_descriptor,
        new java.lang.String[] { "MsgId", "Result", });
    info.xiaomo.server.shared.protocol.msg.MessageId.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
